[common]
executable_name = "/usr/bin/firefox"
share_local_time = false
filter_disk_sync = false
dbus_name = "org.mozilla.*"

[wayland]

[network]

[pulse_audio]

[home_share]
home_paths = [
    "Downloads",
    ".local/share/fonts",
    ".local/share/icons",
    ".local/share/themes",
    ".config/gtk-3.0",
    ".config/gtk-4.0",
]

[direct_rendering]
enable_aco = false

[notify]

[pipewire]

[v4l]

[gnome_toolkit]
gnome_portal = true
