#!/bin/sh

# Power menu script using tofi
# Modified from https://github.com/ericmurphyxyz/dotfiles/blob/master/.local/bin/powermenu

CHOSEN=$(printf "Lock\nSuspend\nReboot\nPower Off\nLog Out" | tofi)

case "$CHOSEN" in
	"Lock") swaylock -f -c 000000 ;;
	"Suspend") swaylock -f -c 000000 && systemctl suspend ;;
	"Reboot") systemctl reboot ;;
	"Power Off") systemctl poweroff ;;
	"Log Out") swaymsg exit ;;
	*) exit 1 ;;
esac
